default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

production:
  <<: *default
  compile: false
  extract_css: true
  cache_manifest: true